In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
data = pd.read_csv("Symptom2Disease.csv")
print(data.head())
encoder = LabelEncoder()
y = encoder.fit_transform(data['label'])
vectorizer = TfidfVectorizer(max_features=100)
X = vectorizer.fit_transform(data['text']).toarray()
X_single = X[:, 0].reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(
    X_single, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("\nPredicted Values:")
print(y_pred[:10])
print("\nActual Values:")
print(y_test[:10])
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("\nMean Squared Error:", mse)
print("R2 Score:", r2)

   Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...

Predicted Values:
[11.64319301  8.70072611 11.64319301 11.64319301 11.64319301 11.64319301
 11.64319301 11.64319301 11.64319301  8.71314655]

Actual Values:
[19 12 16 14 17 22  8 18 14 12]

Mean Squared Error: 46.48788936144288
R2 Score: -0.00028668130496645183


PICKLE PACKAGE

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [ ]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([-9.13461065])

In [ ]:
mp.intercept_

np.float64(11.643193013024373)

In [ ]:
mp.predict([[5000]])

array([-45661.4100448])

JOBLIB PACKAGE

In [ ]:
import joblib

In [ ]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([-9.13461065])

In [ ]:
mj.intercept_

np.float64(11.643193013024373)

In [ ]:
mj.predict([[5000]])

array([-45661.4100448])

ONE HOT ENCODING


In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
data = pd.read_csv("Symptom2Disease.csv")

In [4]:
print(data.head())

   Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...


In [5]:
X = data[['label']]

In [6]:
encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(X)

In [7]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['label'])
)

In [8]:
final_data = pd.concat([data, encoded_df], axis=1)

In [9]:
print(final_data.head())

   Unnamed: 0      label                                               text  \
0           0  Psoriasis  I have been experiencing a skin rash on my arm...   
1           1  Psoriasis  My skin has been peeling, especially on my kne...   
2           2  Psoriasis  I have been experiencing joint pain in my fing...   
3           3  Psoriasis  There is a silver like dusting on my skin, esp...   
4           4  Psoriasis  My nails have small dents or pits in them, and...   

   label_Acne  label_Arthritis  label_Bronchial Asthma  \
0         0.0              0.0                     0.0   
1         0.0              0.0                     0.0   
2         0.0              0.0                     0.0   
3         0.0              0.0                     0.0   
4         0.0              0.0                     0.0   

   label_Cervical spondylosis  label_Chicken pox  label_Common Cold  \
0                         0.0                0.0                0.0   
1                         0.0     

TRAIN TEST SPLIT

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv("Symptom2Disease.csv")

X = data[['label']]
y = data['label']

encoder = OneHotEncoder(sparse_output=False)

X_encoded = encoder.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train shape :", X_train.shape)
print("X_test shape  :", X_test.shape)
print("y_train shape :", y_train.shape)
print("y_test shape  :", y_test.shape)

X_train shape : (960, 24)
X_test shape  : (240, 24)
y_train shape : (960,)
y_test shape  : (240,)
